//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wolfram_Alpha_Keyboard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wolfram_Alpha_Keyboard.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Favourites.
        /// </summary>
        public static string AddToFavourites {
            get {
                return ResourceManager.GetString("AddToFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adviced apps:.
        /// </summary>
        public static string AdvicedApps {
            get {
                return ResourceManager.GetString("AdvicedApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemistry/Biology.
        /// </summary>
        public static string ChemistryBiology {
            get {
                return ResourceManager.GetString("ChemistryBiology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Display.
        /// </summary>
        public static string ClearDisplay {
            get {
                return ResourceManager.GetString("ClearDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Favourites.
        /// </summary>
        public static string ClearFavourites {
            get {
                return ResourceManager.GetString("ClearFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear History.
        /// </summary>
        public static string ClearHistory {
            get {
                return ResourceManager.GetString("ClearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ConfirmText {
            get {
                return ResourceManager.GetString("ConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text correctly copied to clipboard..
        /// </summary>
        public static string CopiedToClipboard {
            get {
                return ResourceManager.GetString("CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolfie Keyboard is an intellectual property of its two creators. It&apos;s not meant to violate any copyright. It isn&apos;t associated in any way to Wolfram Alpha LLC and can&apos;t be considered an official product of theirs..
        /// </summary>
        public static string CopyrightText {
            get {
                return ResourceManager.GetString("CopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy last search URL to Clipboard.
        /// </summary>
        public static string CopyURLtoClipboard {
            get {
                return ResourceManager.GetString("CopyURLtoClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Item.
        /// </summary>
        public static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed by:.
        /// </summary>
        public static string DesignedBy {
            get {
                return ResourceManager.GetString("DesignedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by:.
        /// </summary>
        public static string DevelopedBy {
            get {
                return ResourceManager.GetString("DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing here! Tap and hold a history entry to place it here :-).
        /// </summary>
        public static string EmptyFavourites {
            get {
                return ResourceManager.GetString("EmptyFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t searched for anything yet! Tap on the search box above to get started :-).
        /// </summary>
        public static string EmptyHistory {
            get {
                return ResourceManager.GetString("EmptyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string EmptyListsMessage {
            get {
                return ResourceManager.GetString("EmptyListsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced math keyboards.
        /// </summary>
        public static string EnhancedMathKeyboards {
            get {
                return ResourceManager.GetString("EnhancedMathKeyboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites:.
        /// </summary>
        public static string Favourites {
            get {
                return ResourceManager.GetString("Favourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites management.
        /// </summary>
        public static string FavouritesManagement {
            get {
                return ResourceManager.GetString("FavouritesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features of Wolfie.
        /// </summary>
        public static string FeaturesOfWolfie {
            get {
                return ResourceManager.GetString("FeaturesOfWolfie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funny searches:.
        /// </summary>
        public static string FunnySearches {
            get {
                return ResourceManager.GetString("FunnySearches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get started!.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string Italian {
            get {
                return ResourceManager.GetString("Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Functions:.
        /// </summary>
        public static string OtherFunctions {
            get {
                return ResourceManager.GetString("OtherFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin transparent tile.
        /// </summary>
        public static string PinTransparent {
            get {
                return ResourceManager.GetString("PinTransparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portoguese.
        /// </summary>
        public static string Portoguese {
            get {
                return ResourceManager.GetString("Portoguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this App!.
        /// </summary>
        public static string RateThisApp {
            get {
                return ResourceManager.GetString("RateThisApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent searches:.
        /// </summary>
        public static string RecentSearches {
            get {
                return ResourceManager.GetString("RecentSearches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent searches saving.
        /// </summary>
        public static string RecentSearchesSaving {
            get {
                return ResourceManager.GetString("RecentSearchesSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Wolfie.
        /// </summary>
        public static string ResetApp {
            get {
                return ResourceManager.GetString("ResetApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete any data associated with Wolfie and reset it. Do you wish to continue?.
        /// </summary>
        public static string ResetAppConfirmation {
            get {
                return ResourceManager.GetString("ResetAppConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Wolfie.
        /// </summary>
        public static string ResetAppConfirmationButton {
            get {
                return ResourceManager.GetString("ResetAppConfirmationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats/Trigonometry.
        /// </summary>
        public static string StatsTrigonometry {
            get {
                return ResourceManager.GetString("StatsTrigonometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe to continue   ››.
        /// </summary>
        public static string SwipeToContinue {
            get {
                return ResourceManager.GetString("SwipeToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile is already pinned. Before proceeding, unpin the existing one!.
        /// </summary>
        public static string TileAlreadyPinned {
            get {
                return ResourceManager.GetString("TileAlreadyPinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tongue.
        /// </summary>
        public static string Tongue {
            get {
                return ResourceManager.GetString("Tongue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to make your contribution into Wolfie Keyboard translation and get your name here? Reach me out at:.
        /// </summary>
        public static string TranslationRequest1 {
            get {
                return ResourceManager.GetString("TranslationRequest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for more info! Thanks in advance!.
        /// </summary>
        public static string TranslationRequest2 {
            get {
                return ResourceManager.GetString("TranslationRequest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translators of Wolfie.
        /// </summary>
        public static string TranslatorsHeaderButton {
            get {
                return ResourceManager.GetString("TranslatorsHeaderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translators.
        /// </summary>
        public static string TranslatorsText {
            get {
                return ResourceManager.GetString("TranslatorsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        public static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolfie can solve almost everything, from calculus to quantum physics..
        /// </summary>
        public static string Tutorial1Bottom {
            get {
                return ResourceManager.GetString("Tutorial1Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolfie is an advanced keyboard that allows you to interface the well-known WolframAlpha website..
        /// </summary>
        public static string Tutorial1Top {
            get {
                return ResourceManager.GetString("Tutorial1Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        public static string WelcomeTo {
            get {
                return ResourceManager.GetString("WelcomeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well done!.
        /// </summary>
        public static string WellDone {
            get {
                return ResourceManager.GetString("WellDone", resourceCulture);
            }
        }
    }
}
